modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: []  # Любой код 2xx считается успешным
      method: GET
  tcp_connect:
    prober: tcp
    timeout: 5s
