global:
  scrape_interval: 15s  # Как часто Prometheus будет собирать метрики (раз в 15 секунд)
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files: # Файлы с правилами оповещения.
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'  # Название задачи
    static_configs:
      - targets: ['localhost:9090']  # Сам Prometheus будет собирать свои собственные метрики

# - job_name: "node_exporter"  # Название задачи для мониторинга сервера для Linux
#  static_configs:
#     - targets: ["host.docker.internal:9100"]  # Предполагаем, что Node Exporter работает на порту 9100

  - job_name: 'windows'
    static_configs:
      - targets: ['host.docker.internal:9182']  # можно заменить на ваш IP машины
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]  # По умолчанию проверяем HTTP
    static_configs:
      - targets:
          - http://grafana:3000 # Проверяем Grafana
          - http://sentry:9000  # Проверяем Sentry UI/API
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]  # Проверяем TCP-подключение
    static_configs:
      - targets:
          - sentry-db:5432  # PostgreSQL for Sentry
          - sentry-redis:6379  # Redis for Sentry
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
